### ISSUE TITLE
Fix HAProxy -> Drupal Layer 4 outages

### ISSUE THREAD

**Issue by shaworth** [shaworth/slx_issues#13]
We need to bypass ELB and talk directly between the two servers.

**Comment by shaworth** [comment]
Reconfigured sportslifex.com drupal instance to allow incoming connections to ec2-54-164-3-139.compute-1.amazonaws.com on port 80.  Configured haproxy with a second 'origin server' in the Drupal cluster sending traffic to ec2-54-164-3-139.compute-1.amazonaws.com on port 80.  We now have two different routes between ha_proxy to the backend drupal machine.  If either the compute IP address is changed, or the ELB address is changed, traffic should continue to reach drupal.

![ha_proxy_config](https://cloud.githubusercontent.com/assets/534970/21291864/038f0256-c4bd-11e6-9f03-6dcf8665e533.PNG)

**Comment by donkoller** [comment]
Next time we have to terminate this EC2 instance and relaunch it, will this break?

**Comment by shaworth** [comment]
Don't believe so, used the IP that I ssh to.  Even if it does change IP
address I also am using ELB, so both would need to change at same time.  We
should test to make sure of course.
